### PR TITLE
Combined cleaninfo+waterinfo

### PR DESCRIPTION
**Pull request by dbochicchio**
Hey @mrbungle64 I've added a new event to combine cleaning status with waterinfo. This makes easier in my MQTT bridge to get the real status (ie: mopping or cleaning) in a central and unique place.

### CODE REVIEW

**Review by mrbungle64 — APPROVED** [review]
TODO: Implement method for duplicate code

**Comment by mrbungle64** [comment]
> Hey @mrbungle64 I've added a new event to combine cleaning status with waterinfo. This makes easier in my MQTT bridge to get the real status (ie: mopping or cleaning) in a central and unique place.

Hi @dbochicchio 

I thinkk we have to rename the "CleanReportDetails" event because some models don't have a mopping system.

Which name do you prefer?
* CleanReportWaterbox
* CleanReportWaterInfo
* CleanReportWaterboxInfo

**Comment by mrbungle64** [comment]
@dbochicchio 

I also would like to convert `waterboxInfo` (`enabled` attribute) to boolean:

```js
{
  "status": "idle",
  "waterInfo": {
    "enabled": false,
    "level": 4
  }
}
```

**Comment by dbochicchio** [comment]
@mrbungle64 it's ok for me. I'm using this event to understand when it's starting and if it's mopping or just cleaning, by looking at enabled. You're the maintainer, so it's up to you, I'm good with anything you'll pick ;)

**Pull request merged**
