### PR TITLE
is_ready and fix for consecutives connections

### PR DESCRIPTION
**Pull request by nicoduj**
Removed also 2 console.logs

### CODE REVIEW

**Comment by nicoduj** [comment]
I have also fixed some error on cleanstate report

**Comment by mrbungle64** [comment]
> I have also fixed some error on cleanstate report

I'm not sure if I already know this error.
Is this error maybe only related to Slim 10 model?

**Comment by nicoduj** [comment]
I think it was just a typo in the case, since cleanstate was with cleanspeed instead of cleanreport 

```javascript
        case 'cleanstate':		
        case 'cleanspeed':
```

**Comment by mrbungle64** [comment]
> I think it was just a typo in the case in tool.js, since cleanstate was with cleanspeed instead of cleanreport
> 
> ```js
>         case 'cleanstate':		
>         case 'cleanspeed':
> ```

Ah now I see. Thank you :+1:

**Comment by mrbungle64** [comment]
TODO: Merge example apps `app.js` and `app2.js`

**Comment by boriswerner** [comment]
@nicoduj great, finally we get rid of the error :-)
@mrbungle64 looks good to me

**Pull request merged**
